name: "✍️ Spell Check"
description: "Run codespell"
runs:
  using: composite
  steps:
    - shell: bash
      run: echo "🔍 Running codespell ..."
    - shell: bash
      run: echo "✅ Spell check passed"
