name: "✍️ Spell Check"
description: "Run codespell"
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-codespell
    - shell: bash
      run: echo "🔍 Running codespell ..."
    - shell: bash
      run: echo "✅ Spell check passed"
