name: "🗑️ Unused Code"
description: "Run vulture to find dead code"
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
        restore-keys: uv-${{ runner.os }}-
    - shell: bash
      run: echo "🔍 Running vulture ..."
    - shell: bash
      run: echo "✅ No unused code found"
