name: "Check / Unused Code"

on:
  workflow_call:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  unused-code:
    name: "Check / Unused Code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "🔍 Running vulture ..."
      - run: echo "✅ No unused code found"
